# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir e:/mycode/verilog/decpwmip_repo/edit_dec_pwm_v1_0.cache/wt [current_project]
set_property parent.project_path e:/mycode/verilog/decpwmip_repo/edit_dec_pwm_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths e:/Mycode/Verilog/DecPwmip_repo/dec_pwm_1.0 [current_project]
read_verilog -library xil_defaultlib {
  E:/Mycode/Verilog/DecPwmip_repo/dec_pwm_1.0/hdl/frq_cal.v
  E:/Mycode/Verilog/DecPwmip_repo/dec_pwm_1.0/hdl/pwm.v
  e:/Mycode/Verilog/DecPwmip_repo/dec_pwm_1.0/hdl/dec_pwm_v1_0_S00_AXI.v
  e:/Mycode/Verilog/DecPwmip_repo/dec_pwm_1.0/hdl/dec_pwm_v1_0.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top dec_pwm_v1_0 -part xc7z020clg484-1


write_checkpoint -force -noxdef dec_pwm_v1_0.dcp

catch { report_utilization -file dec_pwm_v1_0_utilization_synth.rpt -pb dec_pwm_v1_0_utilization_synth.pb }
