# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/gps.xdc

# XDC: imports/new/imode.xdc

# XDC: new/delay.xdc

# XDC: imports/new/motor.xdc

# Block Designs: bd/gpsImode/gpsImode.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode || ORIG_REF_NAME==gpsImode}]

# IP: bd/gpsImode/ip/gpsImode_processing_system7_0_0/gpsImode_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_processing_system7_0_0 || ORIG_REF_NAME==gpsImode_processing_system7_0_0}]

# IP: bd/gpsImode/ip/gpsImode_newGpsIp_0_0/gpsImode_newGpsIp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_newGpsIp_0_0 || ORIG_REF_NAME==gpsImode_newGpsIp_0_0}]

# IP: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_axi_uartlite_0_0 || ORIG_REF_NAME==gpsImode_axi_uartlite_0_0}]

# IP: bd/gpsImode/ip/gpsImode_processing_system7_0_axi_periph_0/gpsImode_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==gpsImode_processing_system7_0_axi_periph_0}]

# IP: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==gpsImode_rst_processing_system7_0_100M_0}]

# IP: bd/gpsImode/ip/gpsImode_xbar_0/gpsImode_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_xbar_0 || ORIG_REF_NAME==gpsImode_xbar_0}]

# IP: bd/gpsImode/ip/gpsImode_myImode_0_1/gpsImode_myImode_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_myImode_0_1 || ORIG_REF_NAME==gpsImode_myImode_0_1}]

# IP: bd/gpsImode/ip/gpsImode_myip_fifo_ctrl_0_0/gpsImode_myip_fifo_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_myip_fifo_ctrl_0_0 || ORIG_REF_NAME==gpsImode_myip_fifo_ctrl_0_0}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_0_4/gpsImode_fifo_generator_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_0_4 || ORIG_REF_NAME==gpsImode_fifo_generator_0_4}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_0_5/gpsImode_fifo_generator_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_0_5 || ORIG_REF_NAME==gpsImode_fifo_generator_0_5}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_1_1/gpsImode_fifo_generator_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_1_1 || ORIG_REF_NAME==gpsImode_fifo_generator_1_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_1_2/gpsImode_fifo_generator_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_1_2 || ORIG_REF_NAME==gpsImode_fifo_generator_1_2}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_14_2/gpsImode_fifo_generator_14_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_14_2 || ORIG_REF_NAME==gpsImode_fifo_generator_14_2}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_16_0/gpsImode_fifo_generator_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_16_0 || ORIG_REF_NAME==gpsImode_fifo_generator_16_0}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_16_1/gpsImode_fifo_generator_16_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_16_1 || ORIG_REF_NAME==gpsImode_fifo_generator_16_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_18_0/gpsImode_fifo_generator_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_18_0 || ORIG_REF_NAME==gpsImode_fifo_generator_18_0}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_18_1/gpsImode_fifo_generator_18_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_18_1 || ORIG_REF_NAME==gpsImode_fifo_generator_18_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_19_0/gpsImode_fifo_generator_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_19_0 || ORIG_REF_NAME==gpsImode_fifo_generator_19_0}]

# IP: bd/gpsImode/ip/gpsImode_delay_0_1/gpsImode_delay_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_delay_0_1 || ORIG_REF_NAME==gpsImode_delay_0_1}]

# IP: bd/gpsImode/ip/gpsImode_ch2_fifo2_0/gpsImode_ch2_fifo2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_ch2_fifo2_0 || ORIG_REF_NAME==gpsImode_ch2_fifo2_0}]

# IP: bd/gpsImode/ip/gpsImode_delay1_fifo1_1/gpsImode_delay1_fifo1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_delay1_fifo1_1 || ORIG_REF_NAME==gpsImode_delay1_fifo1_1}]

# IP: bd/gpsImode/ip/gpsImode_delay1_fifo1_2/gpsImode_delay1_fifo1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_delay1_fifo1_2 || ORIG_REF_NAME==gpsImode_delay1_fifo1_2}]

# IP: bd/gpsImode/ip/gpsImode_delay2_fifo1_0/gpsImode_delay2_fifo1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_delay2_fifo1_0 || ORIG_REF_NAME==gpsImode_delay2_fifo1_0}]

# IP: bd/gpsImode/ip/gpsImode_delay2_fifo1_1/gpsImode_delay2_fifo1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_delay2_fifo1_1 || ORIG_REF_NAME==gpsImode_delay2_fifo1_1}]

# IP: bd/gpsImode/ip/gpsImode_delay3_fifo1_0/gpsImode_delay3_fifo1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_delay3_fifo1_0 || ORIG_REF_NAME==gpsImode_delay3_fifo1_0}]

# IP: bd/gpsImode/ip/gpsImode_delay3_fifo2_0/gpsImode_delay3_fifo2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_delay3_fifo2_0 || ORIG_REF_NAME==gpsImode_delay3_fifo2_0}]

# IP: bd/gpsImode/ip/gpsImode_delay4_fifo1_0/gpsImode_delay4_fifo1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_delay4_fifo1_0 || ORIG_REF_NAME==gpsImode_delay4_fifo1_0}]

# IP: bd/gpsImode/ip/gpsImode_start_tri_fifo1_0/gpsImode_start_tri_fifo1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_start_tri_fifo1_0 || ORIG_REF_NAME==gpsImode_start_tri_fifo1_0}]

# IP: bd/gpsImode/ip/gpsImode_motor_angle_fifo1_0/gpsImode_motor_angle_fifo1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_motor_angle_fifo1_0 || ORIG_REF_NAME==gpsImode_motor_angle_fifo1_0}]

# IP: bd/gpsImode/ip/gpsImode_motor_0_0/gpsImode_motor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_motor_0_0 || ORIG_REF_NAME==gpsImode_motor_0_0}]

# IP: bd/gpsImode/ip/gpsImode_auto_pc_0/gpsImode_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_auto_pc_0 || ORIG_REF_NAME==gpsImode_auto_pc_0}]

# XDC: bd/gpsImode/ip/gpsImode_processing_system7_0_0/gpsImode_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_processing_system7_0_0 || ORIG_REF_NAME==gpsImode_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_axi_uartlite_0_0 || ORIG_REF_NAME==gpsImode_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_axi_uartlite_0_0 || ORIG_REF_NAME==gpsImode_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==gpsImode_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==gpsImode_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_xbar_0/gpsImode_xbar_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_0_4/gpsImode_fifo_generator_0_4/gpsImode_fifo_generator_0_4.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_0_4 || ORIG_REF_NAME==gpsImode_fifo_generator_0_4}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_0_4/gpsImode_fifo_generator_0_4_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_0_5/gpsImode_fifo_generator_0_5/gpsImode_fifo_generator_0_5.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_0_5 || ORIG_REF_NAME==gpsImode_fifo_generator_0_5}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_0_5/gpsImode_fifo_generator_0_5_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_1_1/gpsImode_fifo_generator_1_1/gpsImode_fifo_generator_1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_1_1 || ORIG_REF_NAME==gpsImode_fifo_generator_1_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_1_1/gpsImode_fifo_generator_1_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_1_2/gpsImode_fifo_generator_1_2/gpsImode_fifo_generator_1_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_1_2 || ORIG_REF_NAME==gpsImode_fifo_generator_1_2}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_1_2/gpsImode_fifo_generator_1_2_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_14_2/gpsImode_fifo_generator_14_2/gpsImode_fifo_generator_14_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_14_2 || ORIG_REF_NAME==gpsImode_fifo_generator_14_2}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_14_2/gpsImode_fifo_generator_14_2_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_16_0/gpsImode_fifo_generator_16_0/gpsImode_fifo_generator_16_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_16_0 || ORIG_REF_NAME==gpsImode_fifo_generator_16_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_16_0/gpsImode_fifo_generator_16_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_16_1/gpsImode_fifo_generator_16_1/gpsImode_fifo_generator_16_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_16_1 || ORIG_REF_NAME==gpsImode_fifo_generator_16_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_16_1/gpsImode_fifo_generator_16_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_18_0/gpsImode_fifo_generator_18_0/gpsImode_fifo_generator_18_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_18_0 || ORIG_REF_NAME==gpsImode_fifo_generator_18_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_18_0/gpsImode_fifo_generator_18_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_18_1/gpsImode_fifo_generator_18_1/gpsImode_fifo_generator_18_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_18_1 || ORIG_REF_NAME==gpsImode_fifo_generator_18_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_18_1/gpsImode_fifo_generator_18_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_19_0/gpsImode_fifo_generator_19_0/gpsImode_fifo_generator_19_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_19_0 || ORIG_REF_NAME==gpsImode_fifo_generator_19_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_19_0/gpsImode_fifo_generator_19_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_ch2_fifo2_0/gpsImode_ch2_fifo2_0/gpsImode_ch2_fifo2_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_ch2_fifo2_0 || ORIG_REF_NAME==gpsImode_ch2_fifo2_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_ch2_fifo2_0/gpsImode_ch2_fifo2_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_delay1_fifo1_1/gpsImode_delay1_fifo1_1/gpsImode_delay1_fifo1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_delay1_fifo1_1 || ORIG_REF_NAME==gpsImode_delay1_fifo1_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_delay1_fifo1_1/gpsImode_delay1_fifo1_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_delay1_fifo1_2/gpsImode_delay1_fifo1_2/gpsImode_delay1_fifo1_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_delay1_fifo1_2 || ORIG_REF_NAME==gpsImode_delay1_fifo1_2}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_delay1_fifo1_2/gpsImode_delay1_fifo1_2_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_delay2_fifo1_0/gpsImode_delay2_fifo1_0/gpsImode_delay2_fifo1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_delay2_fifo1_0 || ORIG_REF_NAME==gpsImode_delay2_fifo1_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_delay2_fifo1_0/gpsImode_delay2_fifo1_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_delay2_fifo1_1/gpsImode_delay2_fifo1_1/gpsImode_delay2_fifo1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_delay2_fifo1_1 || ORIG_REF_NAME==gpsImode_delay2_fifo1_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_delay2_fifo1_1/gpsImode_delay2_fifo1_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_delay3_fifo1_0/gpsImode_delay3_fifo1_0/gpsImode_delay3_fifo1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_delay3_fifo1_0 || ORIG_REF_NAME==gpsImode_delay3_fifo1_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_delay3_fifo1_0/gpsImode_delay3_fifo1_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_delay3_fifo2_0/gpsImode_delay3_fifo2_0/gpsImode_delay3_fifo2_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_delay3_fifo2_0 || ORIG_REF_NAME==gpsImode_delay3_fifo2_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_delay3_fifo2_0/gpsImode_delay3_fifo2_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_delay4_fifo1_0/gpsImode_delay4_fifo1_0/gpsImode_delay4_fifo1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_delay4_fifo1_0 || ORIG_REF_NAME==gpsImode_delay4_fifo1_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_delay4_fifo1_0/gpsImode_delay4_fifo1_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_start_tri_fifo1_0/gpsImode_start_tri_fifo1_0/gpsImode_start_tri_fifo1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_start_tri_fifo1_0 || ORIG_REF_NAME==gpsImode_start_tri_fifo1_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_start_tri_fifo1_0/gpsImode_start_tri_fifo1_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_motor_angle_fifo1_0/gpsImode_motor_angle_fifo1_0/gpsImode_motor_angle_fifo1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_motor_angle_fifo1_0 || ORIG_REF_NAME==gpsImode_motor_angle_fifo1_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_motor_angle_fifo1_0/gpsImode_motor_angle_fifo1_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_auto_pc_0/gpsImode_auto_pc_0_ooc.xdc

# XDC: bd/gpsImode/gpsImode_ooc.xdc
